import Layout from "@/components/templates/Layout";
// import { Vazirmatn } from "next/font/google";
import TanstackQueryProvider from "@/components/partials/providers/TanstackQueryProvider";
import { getCookie } from "@/lib/cookie";
import { Toaster } from "react-hot-toast";
import "./globals.css";

// const vazirmatn = Vazirmatn({
//   variable: "--font-vazirmatn",
//   // subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getProfile = async () => {
  const res = await fetch(`${process.env.BASE_URL}/user/profile`, {
    cache: "no-store",
    headers: {
      Authorization: `Bearer ${await getCookie("accessToken")}`,
    },
  });

  if (!res.ok) {
    if (res.status !== 403) {
      throw new Error("Failed to fetch profile");
    }
  }
  return res.json();
};

export default async function RootLayout({ children }) {
  const userProfile = await getProfile();
  return (
    // <html lang="fa" dir="rtl" className={`${vazirmatn.variable}`}>
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://lib.arvancloud.ir/font-awesome/6.3.0/css/all.css"
        />
      </head>
      <body suppressHydrationWarning>
        <TanstackQueryProvider>
          <Layout data={userProfile}>{children}</Layout>
        </TanstackQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
